### ISSUE TITLE
Registering an account not working

### ISSUE THREAD

**Issue by ITconsultants247** [steere/AdminLTE#1]
Not sure how far this app should run, but when I ran the app I was prompted first with the login page.  Then, from there, I navigated to the sign up page and entered my account credentials to register a demo user account. Clicking the Register button resulted in a website hangup.  I can verify that all identity tables have been created but they remain empty from any record.  Is this by design, or I'm missing something?  I'm new to the .net core framework.

**Comment by artmasters200** [comment]
did you do the DB migration? I believe there would be a page asking for your permission to migrate. You can also check the folder \AdminLTE\Data\Migrations

**Comment by moemura** [comment]
disable function useSubmitClass() in site.js will help
